// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYxeWrcC1z2TxqHeuFB_PdO0JcSVRLAng',
    appId: '1:641089933557:web:c61e7149dae436eb90f5bc',
    messagingSenderId: '641089933557',
    projectId: 'uyiraran',
    authDomain: 'uyiraran.firebaseapp.com',
    storageBucket: 'uyiraran.firebasestorage.app',
    measurementId: 'G-QV64NVC45Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgXyzNv3qF-qg81gR5cScBae0Z7GrGpo',
    appId: '1:641089933557:android:c590cc70ba9acf2490f5bc',
    messagingSenderId: '641089933557',
    projectId: 'uyiraran',
    storageBucket: 'uyiraran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA3vMyCRf_6VunTdQ47dePmcSBzBSM4cc',
    appId: '1:641089933557:ios:3875ba1bdc6cb4b990f5bc',
    messagingSenderId: '641089933557',
    projectId: 'uyiraran',
    storageBucket: 'uyiraran.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA3vMyCRf_6VunTdQ47dePmcSBzBSM4cc',
    appId: '1:641089933557:ios:3875ba1bdc6cb4b990f5bc',
    messagingSenderId: '641089933557',
    projectId: 'uyiraran',
    storageBucket: 'uyiraran.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYxeWrcC1z2TxqHeuFB_PdO0JcSVRLAng',
    appId: '1:641089933557:web:4446b6271529f40d90f5bc',
    messagingSenderId: '641089933557',
    projectId: 'uyiraran',
    authDomain: 'uyiraran.firebaseapp.com',
    storageBucket: 'uyiraran.firebasestorage.app',
    measurementId: 'G-VV9D27C4DY',
  );
}
